#!/bin/sh
set -eu

LEDGER_DIR="${LEDGER_DIR:-/ledger}"
LEDGER_FILE="${LEDGER_FILE:-${LEDGER_DIR}/main.bean}"
PRICES_FILE="${PRICES_FILE:-${LEDGER_DIR}/prices.bean}"
UPDATE_RATE="${UPDATE_RATE:-daily}"
WORKERS="${WORKERS:-4}"
BACKFILL="${BACKFILL:-false}"

mkdir -p "$(dirname "$PRICES_FILE")"
touch "$PRICES_FILE"

tmp_prices="$(mktemp)"
tmp_errors="$(mktemp)"
cleanup() {
    rm -f "$tmp_prices" "$tmp_errors"
}
trap cleanup EXIT

if [ "$BACKFILL" = "true" ]; then
    if ! bean-price --update --update-rate "$UPDATE_RATE" --inactive --workers "$WORKERS" "$LEDGER_FILE" >"$tmp_prices" 2>"$tmp_errors"; then
        cat "$tmp_errors" >&2
        exit 1
    fi
else
    if ! bean-price --inactive --workers "$WORKERS" "$LEDGER_FILE" >"$tmp_prices" 2>"$tmp_errors"; then
        cat "$tmp_errors" >&2
        exit 1
    fi
fi

if [ -s "$tmp_errors" ]; then
    cat "$tmp_errors" >&2
fi

if [ ! -s "$tmp_prices" ]; then
    echo "No new prices to append."
    exit 0
fi

{
    printf '\n; Prices generated by bean-price on %s UTC\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    cat "$tmp_prices"
} >> "$PRICES_FILE"

echo "Appended new prices to $PRICES_FILE."
